"use strict";
var userController_1 = require('./userController');
var express = require('express');
var auth = require('./login/loginService');
var router = express.Router();
router.get('/', userController_1.default.getAll);
router.post('/', userController_1.default.create);
router.post('/createpublicuser', userController_1.default.createPublicUser);
router.get('/', auth.hasRole('admin'), userController_1.default.getAll);
router.get('/\\$count', userController_1.default.getAll);
router.get('/:id', auth.hasRole('admin'), userController_1.default.getById);
router.get('/me', auth.isAuthenticated(), userController_1.default.me);
router.put('/me/changepassword', auth.isAuthenticated(), userController_1.default.changePassword);
router.put('/', auth.isAuthenticated(), userController_1.default.update);
router.delete('/:id', auth.hasRole('admin'), userController_1.default.remove);
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = router;
